[workspace]
resolver = "2"

members = [
    "bevy_immersed_app",
]

[workspace.package]
version = "0.0.1"
authors = ["Yongda Fan"]
description = "stream your computer screen into vr headset"
repository = "https://github.com/LogicFan/xr-workspace"
